[default.limits]
form = "64 kB"
data-form = "10 MiB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "10 MiB"
"file/gif" = "10 MiB"
"file/png" = "10 MiB"
"file/svg" = "10 MiB"
"file/mp4" = "10 MiB"
"file/mov" = "10 MiB"
"file/webm" = "10 MiB"
"file/webp" = "10 MiB"

[default.databases.test]
url = "db/test.db"